"""Train an AMR classifier from sparse k-mer features with dimensionality reduction.

This script is designed for low-memory machines (for example 16 GB RAM).
It works from files generated by the sparse wide pipeline:
  - kmer_matrix_sparse.npz
  - kmer_matrix_genome_index.csv
and builds labels from:
  - data/BVBRC_genome_amr.csv

Example usage:
  python scripts/train_sparse_dimred.py --antibiotic ampicillin

Optional tuning:
  python scripts/train_sparse_dimred.py --antibiotic ciprofloxacin --top-k 50000 --svd-components 300
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.sparse import load_npz
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    balanced_accuracy_score,
    classification_report,
    f1_score,
    precision_recall_fscore_support,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MaxAbsScaler


# Same phenotype mapping used in your notebook workflow.
PHENOTYPE_MAP = {
    "Susceptible": 0,
    "Intermediate": 1,
    "Resistant": 2,
    "Nonsusceptible": 2,
}


def build_labels_matrix(amr_csv_path: Path) -> pd.DataFrame:
    """Build a GenomeID x Antibiotic label matrix from BVBRC AMR records.

    Steps:
    1) keep rows with known phenotype labels,
    2) map string labels to numeric classes,
    3) pivot to wide antibiotics columns.
    """
    amr_df = pd.read_csv(amr_csv_path)

    clean_df = amr_df[amr_df["Resistant Phenotype"].isin(PHENOTYPE_MAP.keys())].copy()
    clean_df["Phenotype_Code"] = clean_df["Resistant Phenotype"].map(PHENOTYPE_MAP)

    labels = clean_df.pivot_table(
        index="Genome ID",
        columns="Antibiotic",
        values="Phenotype_Code",
        aggfunc="max",
    ).reset_index()

    # Normalize key name to match sparse feature row index file.
    labels = labels.rename(columns={"Genome ID": "GenomeID"})
    labels["GenomeID"] = labels["GenomeID"].astype(str)
    return labels


def get_feature_and_target(
    X_sparse,
    genome_index_df: pd.DataFrame,
    labels_df: pd.DataFrame,
    antibiotic: str,
):
    """Align sparse feature rows with labels for one antibiotic.

    The sparse matrix row order is defined by kmer_matrix_genome_index.csv.
    We merge using GenomeID, then subset rows from X_sparse by row index.
    """
    if antibiotic not in labels_df.columns:
        available = ", ".join(sorted([c for c in labels_df.columns if c != "GenomeID"]))
        raise ValueError(
            f"Antibiotic '{antibiotic}' not found in labels. Available: {available}"
        )

    # Keep only genomes that have a non-missing label for the selected antibiotic.
    y_map = labels_df[["GenomeID", antibiotic]].dropna().copy()
    y_map = y_map.rename(columns={antibiotic: "y"})

    aligned = genome_index_df.merge(y_map, on="GenomeID", how="inner")
    if aligned.empty:
        raise ValueError(
            f"No overlapping genomes between sparse matrix rows and labels for '{antibiotic}'."
        )

    # Pull matching rows from the sparse matrix.
    row_idx = aligned["row"].to_numpy(dtype=int)
    X = X_sparse[row_idx]
    y = aligned["y"].to_numpy(dtype=int)

    return X, y, aligned


def build_pipeline(top_k: int, svd_components: int) -> Pipeline:
    """Create a memory-friendly modeling pipeline.

    Segment summary:
    - MaxAbsScaler: sparse-safe scaling without densifying.
    - SelectKBest(chi2): keeps strongest non-negative k-mer signals.
    - TruncatedSVD: sparse dimensionality reduction (PCA alternative for sparse data).
    - LogisticRegression(saga): sparse-friendly linear classifier.
    """
    return Pipeline(
        steps=[
            ("scale", MaxAbsScaler()),
            ("select", SelectKBest(score_func=chi2, k=top_k)),
            ("svd", TruncatedSVD(n_components=svd_components, random_state=42)),
            (
                "clf",
                LogisticRegression(
                    solver="saga",
                    max_iter=3000,
                    multi_class="auto",
                    n_jobs=-1,
                    random_state=42,
                ),
            ),
        ]
    )


def parse_args() -> argparse.Namespace:
    """Collect command-line arguments so experiments are easy to repeat."""
    parser = argparse.ArgumentParser(
        description="Train sparse + dimensionality-reduced AMR model for one antibiotic."
    )
    parser.add_argument(
        "--antibiotic",
        type=str,
        required=True,
        help="Antibiotic column name in AMR labels, e.g., ampicillin",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=50_000,
        help="Number of features to keep after chi2 selection (memory/performance tradeoff)",
    )
    parser.add_argument(
        "--svd-components",
        type=int,
        default=300,
        help="Number of TruncatedSVD components",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.2,
        help="Fraction of data for test split",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed for reproducibility",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Resolve project-relative paths so the script can run from anywhere.
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent

    sparse_matrix_path = project_root / "kmer_matrix_sparse.npz"
    genome_index_path = project_root / "kmer_matrix_genome_index.csv"
    amr_csv_path = project_root / "data" / "BVBRC_genome_amr.csv"

    # Load sparse features and row index mapping.
    print("Loading sparse matrix and genome index...")
    X_sparse = load_npz(sparse_matrix_path)
    genome_index_df = pd.read_csv(genome_index_path)
    genome_index_df["GenomeID"] = genome_index_df["GenomeID"].astype(str)

    # Build antibiotic labels from raw AMR table.
    print("Building label matrix from AMR records...")
    labels_df = build_labels_matrix(amr_csv_path)

    # Align rows and labels for the selected antibiotic.
    print(f"Aligning features with labels for antibiotic: {args.antibiotic}")
    X, y, aligned = get_feature_and_target(
        X_sparse=X_sparse,
        genome_index_df=genome_index_df,
        labels_df=labels_df,
        antibiotic=args.antibiotic,
    )

    # Basic sanity checks to prevent invalid training runs.
    class_counts = pd.Series(y).value_counts().sort_index()
    print("Class counts (0=Susceptible, 1=Intermediate, 2=Resistant):")
    print(class_counts.to_string())

    if len(class_counts) < 2:
        raise ValueError("Need at least 2 classes to train a classifier.")

    # Split with stratification to preserve class proportions in train/test.
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=args.test_size,
        random_state=args.random_state,
        stratify=y,
    )

    # Guard against impossible parameter combinations on small datasets.
    effective_top_k = min(args.top_k, X_train.shape[1])
    effective_svd = min(args.svd_components, max(2, effective_top_k - 1))

    print(
        f"Training with top_k={effective_top_k}, svd_components={effective_svd}, "
        f"train_samples={X_train.shape[0]}, test_samples={X_test.shape[0]}"
    )

    # Build and fit the sparse-aware dimensionality reduction + classifier pipeline.
    model = build_pipeline(top_k=effective_top_k, svd_components=effective_svd)
    model.fit(X_train, y_train)

    # Evaluate on the holdout split.
    y_pred = model.predict(X_test)
    bal_acc = balanced_accuracy_score(y_test, y_pred)
    w_f1 = f1_score(y_test, y_pred, average="weighted")
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_test, y_pred, average="weighted", zero_division=0
    )

    print("\nEvaluation summary:")
    print(f"Balanced accuracy: {bal_acc:.4f}")
    print(f"Weighted precision: {prec:.4f}")
    print(f"Weighted recall:    {rec:.4f}")
    print(f"Weighted F1:        {w_f1:.4f}")

    print("\nDetailed report:")
    print(classification_report(y_test, y_pred, zero_division=0))

    # Optional: save predictions for later error analysis.
    out_dir = project_root / "output"
    out_dir.mkdir(exist_ok=True)
    pred_out = out_dir / f"predictions_{args.antibiotic.replace('/', '_')}.csv"

    # Recover test row mapping for traceability.
    # aligned rows correspond to X/y order before train_test_split.
    all_idx = np.arange(len(y))
    _, test_idx = train_test_split(
        all_idx,
        test_size=args.test_size,
        random_state=args.random_state,
        stratify=y,
    )
    test_meta = aligned.iloc[test_idx].copy()
    test_meta["y_true"] = y_test
    test_meta["y_pred"] = y_pred
    test_meta.to_csv(pred_out, index=False)

    print(f"Saved test predictions: {pred_out}")


if __name__ == "__main__":
    main()
